#pragma once


enum ENotification
  {
  OBJECT_ADDED,
  OBJECT_REMOVED,
  BEFORE_CHILD_DELETE,
  BEFORE_OBJECT_REMOVED,
  PARENT_CHANGED,
  COLOR_CHANGED,
  LABEL_CHANGED,
  BEFORE_POINT_CHANGED,
  POINT_CHANGED,
  OBJECT_SELECTED,
  OBJECT_DSELECTED,
  COORDINATE_Y_CHANGED
  };